package com.thegame.rpg.ui

import androidx.compose.ui.graphics.Color

/**
 * Source-native named-location masters.
 *
 * These 128x64 maps replace procedural placeholder geometry one named location at a time.
 * Temporary story-state props remain separate layers so architecture is reusable.
 */
object PixelSceneCatalog {
    const val PLATFORM_NINE_SCENE_ID = "PLATFORM_NINE_BLACKOUT_SCENE"
    const val RELAY_WORKBENCH_SCENE_ID = "RELAY_WORKBENCH_DEFAULT_SCENE"
    const val GATE_TWELVE_SCENE_ID = "GATE_TWELVE_SEALED_SCENE"
    const val SERVICE_TUNNEL_SCENE_ID = "SERVICE_TUNNEL_DEFAULT_SCENE"
    const val EVAC_STAIR_SCENE_ID = "EVAC_STAIR_DEFAULT_SCENE"
    const val TRACE_CHAMBER_SCENE_ID = "TRACE_CHAMBER_IDLE_SCENE"
    const val DISTRICT_PLAZA_SCENE_ID = "DISTRICT_PLAZA_OPEN_SCENE"
    const val DISTRICT_ARCHIVE_SCENE_ID = "DISTRICT_ARCHIVE_DEFAULT_SCENE"
    const val WORKSHOP_ROW_SCENE_ID = "WORKSHOP_ROW_DEFAULT_SCENE"

    val platformNineBlackout = PixelSprite(
        assetId = PLATFORM_NINE_SCENE_ID,
        width = 128,
        height = 64,
        palette = mapOf(
            'B' to Color(0xFF111A20),
            'F' to Color(0xFF1B252C),
            'W' to Color(0xFF17242B),
            'D' to Color(0xFF10181D),
            'P' to Color(0xFF26363E),
            'A' to Color(0xFF304149),
            'M' to Color(0xFF394850),
            'L' to Color(0xFF53616A),
            'R' to PixelColors.Danger,
            'C' to PixelColors.Cyan,
            'G' to PixelColors.Gold,
            'p' to PixelColors.Paper,
        ),
        rows = listOf(
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
            "DDDDDDDPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDDDDDDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDDDDDDDDDDPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDDDDDDDD",
            "DDDALADPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDALADDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDDDDALADDDPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDALADDDD",
            "DDDALADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDALADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDALADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDALADDDD",
            "DDDALADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDALADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDALADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDALADDDD",
            "MMMALAMMMMMpppppMMMMMMMpppppMMMMMMMMMMMALAMMMMMMpppppMMMMMMMMpppppMMMMMMMMMpppppMMALAMMMMMMMMMMMMMMMMMMpppppMMMMMMMpppppMALAMMMM",
            "MMMALAMMMMMpppppMMMMMMMpppppMMMMMMMMMMMALAMMMMMMpppppMMMMMMMMpppppMMMMMMMMMpppppMMALAMMMMMMMMMMMMMMMMMMpppppMMMMMMMpppppMALAMMMM",
            "MMMALAMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMALAMMMMMMMCCCMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMALAMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMAMMMM",
            "BBBALABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBALABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBALAMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMABBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBB",
            "BBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMLLLMMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMMMLLBB",
            "BBLLMMMLLLLLLLLAALLLLLLLLLLLLLLLLLLMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMCMLLLMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMMMBB",
            "BBWWMLMDDDDDDDDDDDDDDDDDDDDDDDDDDDWMLMPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPMCMWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDLLLLLLLLLLLLLLLLLLLLLLLLLDWMLMPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPMCMWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAAAMMMLMBB",
            "BBWWMLMDPPPPPPPPPPPPPPPPPPPPPPPPPDWMLMPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMCMWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDPPWWWWWWWWWWWWWWWWWWWWWPPDWMLMPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDPPWWWWWWWWWWWWWWWWWWWWWPPDWMLMPPALLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLLLPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADDDDDDDDDDDAAADDDDDDDDDDDAAADDDDDDDDDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWWWWWWWWWDAAADWWWWWWWWWDAAADWWWWWWWDAPPMMWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMAABB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWPPPPPPPWDAAADWPPPPPPPWDAAADWPPPPPWDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMAABB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWPPPPPPPWDAAADWPPPPPPPWDAAADWPPPPPWDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMGGBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWWWWWWWWWDAAADWWWWWWWWWDAAADWWWWWWWDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMGGBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWBBBBBBBWDAAADWBBBBBBBWDAAADWBBBBBWDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMGGBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWBCCCCCBWDAAADWBDDDDDBWDAAADWDDDDBWDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMAABB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWBCCCCCBWDAAADWBDDDDDBWDAAADWDDDDBWDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMAABB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWBCCCCCBWDAAADWBDDDDDBWDAAADWDDDDBWDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMCCBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWBBBBBBBWDAAADWBBBBBBBWDAAADWBBBBBWDAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMCCBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWBBBBBBBWDAAADWBBBBBBBWDAAADWBBBMMMMMPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMAABB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMLMPPADWBBBBBBBWDAAADWBBBBBBBWDAAADWBBBMLLLMPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMMPPWWWWWWWWWWWWWWWWWWWWWPPMWMAAPPADWWWWWWWWWDAAADWWWWWWWWWDAAADWWWWMMMMMPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDPPWWWWWWWWWWWWWWWWWWWWWPPDWMLMPPADWMMMMMMMWDAAADWMMMMMMMWDAAADWMMMMLLLMPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDPPWWWWWWWWWWWWWWWWWWWWWPPDWMLMPPADDDDDDDDDDDAAADDDDDDDDDDDAAADDDDDMMMMMPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDPPPPPPPPPPPPPPPPPPPPPPPPPDWMLMPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMLLLMPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDPPPPPPPPPPPPPPPPPPPPPPPPPDWMLMPPADGGGDDGGGDDCCCDDGGGDDGGGDDCCCDDDDMMMMMPPWLLMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDAAAAAAAAAAAAAAAAAAAAAAAAADWMLMPPADGGGDDGGGDDCCCDDGGGDDGGGDDCCCDDDDDDDAAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMDDAAAAAAAAAAAAAAAAAAAAAAADDWMLMPPADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMWWADDDDDDDDDAADDDDDDDDDAAWWWMLMPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMLMWWADDDDDDDDDAADDDDDDDDDAAWWWMLMPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPWWWMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWAMLMAAAAACCCCAAAAAAAAAGGGAAAAAAAMLMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMMMAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAMMMLMBB",
            "BBWWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMMMMMBB",
            "BBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBB",
            "BBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBB",
            "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
            "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
            "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFGGpFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFRRRRRRRRRRDFFFRRRRRRRRDFFFRRRRRRRRRRRDFFFRRRRRRRRDFFFFRRRRRRRRRDFFFFFRRRRRRRDFFFGGpRRRRRRRRDFFFFFFRRRRRRRRDFFFFFRRRRRRRRRRDFF",
            "FFFRRRRRRRRRRDFFFRRRRRRRRDFFFRRRRRRRRRRRDFFFRRRRRRRRDFFFFRRRRRRRRRDFFFFFRRRRRRRDFFFGGpRRRRRRRRDFFFFFFRRRRRRRRDFFFFFRRRRRRRRRRDFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFGGpFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "FFFFFFFFCCCCCCFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFCCCCCCFFFFFFFFFFFFFFFFFFCCCCCFGGpFFFFFFFFFFCCCCCCFFFFFFFFFFFFFFFFCCCCCFFFFF",
            "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
            "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
            "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
            "BBBBDDDDMMDDDDDDDDDDDDDDDMMDDDDDDDDDDDDDDDMMDDDDDDDDDDDDDDDMMDDDDDDDDDDDDDDDMMDDDDDDDDDDDDDDDMMDDDDDDDDDDDDDDDMMDDDDDDDDDDDDBBBB",
            "BBBBDDDDMMDDDDDDDDCCDDDDDMMDDDDDDDDDDDDDDDCCDDDDDDDDDDDDDDDMMDDDDDCCDDDDDDDDMMDDDDDDDDDDDDCCDMMDDDDDDDDDDDDDDDMMDDCCDDDDDDDDBBBB",
            "BBBBFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFBBBB",
            "BBBBFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFFFFMMFFFFFFFFFFFFBBBB",
            "BBBBDDAAAAAADDDDDDDDDDDAAAAAADDDDDDDDDDDAAAAAADDDDDDDDDDDAAAAAADDDDDDDDDDDAAAAAADDDDDDDDDDDAAAAAADDDDDDDDDDDAAAAAADDDDDDDDDDBBBB",
            "BBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBB",
            "BBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBB",
        ),
    )

    val relayWorkbenchDefault = PixelSprite(
        assetId = RELAY_WORKBENCH_SCENE_ID,
        width = 128,
        height = 64,
        palette = mapOf(
            'B' to Color(0xFF111A20),
            'F' to Color(0xFF1B252C),
            'D' to Color(0xFF162129),
            'P' to Color(0xFF26363E),
            'A' to Color(0xFF303E45),
            'M' to Color(0xFF48535A),
            'L' to Color(0xFF65737A),
            'R' to PixelColors.Danger,
            'C' to PixelColors.Cyan,
            'G' to PixelColors.Gold,
            'H' to Color(0xFFD29A55),
        ),
        rows = listOf(
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
            "DDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDD",
            "DDDDDPPPPPPPLLPPPPPPPPPPPPPPPPPPPPLLPPPPPPPPPPPPPPPPPPPPPPLLPPPPPPPPPPPPPPPPPPPPPPLLPPPPPPPPPPPPPPPPPPPPPPLLPPPPPPPPPPPPPPPDDDDD",
            "DDDDDPPPPPPPLLPPPPGGGGGPPPPPPPPPPPLLPPPPPPPPPCCCCCPPPPPPPPLLPPPPPPPPPPPGGGGGPPPPPPLLPPPPPPPPPPPPPPCCCCCPPPLLPPPPPPPPPPPPPPPDDDDD",
            "DDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDDDDLLDDDDDDDDDDDDDDDDDDDD",
            "MMMMMMMMMMMMLLMMMMMMMMMMMMMMMMMMMMLLMMMMMMMMMMMMMMMMMMMMMMLLMMMMMMMMMMMMMMMMMMMMMMLLMMMMMMMMMMMMMMMMMMMMMMLLMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
            "FFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAF",
            "FFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAF",
            "FFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAFFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFFFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAF",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
            "FFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAFFAADDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDAAFFFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAF",
            "FFAMAMMMMMMMMMMMMMMMMMMMMMFFFAMAFFAADDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDAAFFFAMAFFMMMMMMMMMMMMMMMMMMMMMFAMAF",
            "FFAMAMMMMMMMMMMMMMMMMMMMMMFFFAMAFFAADDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDAAFFFAMAFFMMMMMMMMMMMMMMMMMMMMMFAMAF",
            "FFAMAMMPPPPPPPPPPPDDDDPPMMFFFAMAFFAADDDDDDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDDDDDAAFFFAMAFFMMPPPPPPPPPPPPPPPPPMMFAMAF",
            "FFAMAMMPPGGGPPLLPPDDDDPPMMFFFAMAFFAADDDDDDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDDDDDAAFFFAMAFFMMAAAAAAAPPAAAAAAAPMMFAMAF",
            "FFAMAMMPPGGGPPLLPPDDDDPPMMFFFAMAFFAADDMMDDDDDDDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDDDMMDDAAFFFAMAFFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMPPGGGPPLLPPDDDDPPMMFFFAMAFFAADDMMDDDDDDDDPPPPCCCCCCCCPPPPPPPPGGGGGGGGPPPPDDDDDDDDMMDDAAFFFAMAFFMMADCCDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMPPGGGPPLLPPDDDDPPMMFFFAMAFFAADDMMDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDMMDDAAFFFAMAFFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMAAAAAAAAAAAAAAAAAMMFFFAMAFFAADDMMDLLLLDDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDLLLLDMMDDAAFFFAMAFFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMAAAAAAAAAAAAAAAAAMMFFFAMAFFAADDMMDLLLLDDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDLLLLDMMDDAAFFFAMAFFMMAAAAAAAPPAAAAAAAPMMFAMAF",
            "FFAMAMMPPDDDDDDPPCCCCCPPMMFFFAMAFFAADDMMDDDDDDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDDDDDDMMDDAAAAAAAAAAMMPPPPPPPPPPPPPPPPPMMFAMAF",
            "FFAMAMMPPDDDDDDPPCCCCCPPMMFFFAMAFFAADDMMDDDDDDDDPPBBDDDDDDDDDDDDDDDDDDDDDDDDBBPPDDDDDDDDMMDDAAAAAAAAAAMMPPPPPPPPPPPPPPPPPMMFAMAF",
            "FFAMAMMPPDDDDDDPPCCCCCPPMMFFFAMAFFAADDMMDDDDDDDDPPBBDDDDDDDDDDDDDDDDDDDDDDDDBBPPDDDDDDDDMMDDAAFFAAMAFFMMAAAAAAAPPAAAAAAAPMMFAMAF",
            "FFAMAMMPPDDDDDDPPCCCCCPPMMFFFAMAFFAADDMMDLLLLDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDLLLLDMMDDAAFFAAMAFFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMPPPPPPPPPPPPPPPPPMMFFFAMAFFAADDMMDLLLLDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDLLLLDMMDDAAFFAAMAFFMMADDDDDAPPADGGDDAPMMFAMAF",
            "FFAMAMMAAAAAAAAAAAAAAAAAMMFFFAMAFFAADDMMDDDDDDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDDDDDDMMDDAAFFACMAFFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMAAAAAAAAAAAAAAAAAMMFFFAMAFFAADDMMDDDDDDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDDDDDDMMDDAAFFACMAFFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMPPLLLPPDDDDDDDPPPMMFFFAMAFFAADDMMDDDDDDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDDDDDDMMDDAAFFACMAFFMMAAAAAAAPPAAAAAAAPMMFAMAF",
            "FFAMAMMPPLLLPPDDDDDDDPPPMMFFFAMAFFAADDMMDLLLLDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDLLLLDMMDDAAFFACMAFFMMPPPPPPPPPPPPPPPPPMMFAMAF",
            "FFAMAMMPPLLLPPDDDDDDDPPPMMFFFAMAFFAADDMMDLLLLDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDLLLLDMMDDAAFFAAMAFFMMPPPPPPPPPPPPPPPPPMMFAMAF",
            "FFAMAMMPPLLLPPDDDDDDDPPPMMFFFAMAFFAADDDDDDDDDDDDPPBBBBBBBBBBBBBBBBBBBBBBBBBBBBPPDDDDDDDDDDDDAAFFAAMAFFMMAAAAAAAPPAAAAAAAPMMFAMAF",
            "FFAMAMMPPPPPPPPPPPPPPPPPMMFFFAMAFFAADDDDDDDDDDDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDDDDDDDAAFFAAMAFFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMAAAAAAAAAAAAAAAAAMMFFFAMAFFAAAAAAAAAAAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAFFFAMAFFMMADHHDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMAAAAAAAAAAAAAAAAAMMFDDDDDDFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFDDDDDDFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMPHHHHHHPPDDDDDDPPMMFDDLLDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDLLDDFMMADDDDDAPPADDDDDAPMMFAMAF",
            "FFAMAMMPHHHHHHPPDDDDDDPPMMFDDLLDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDLLDDFMMAAAAAAAPPAAAAAAAPMMFAMAF",
            "FFAMAMMPHHHHHHPPDDDDDDPPMMFDDLLDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDLLDDFMMPPPPPPPPPPPPPPPPPMMFAMAF",
            "FFAMAMMMMMMMMMMMMMMMMMMMMMFDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDFMMMMMMMMMMMMMMMMMMMMMFAMAF",
            "FFAMAMMMMMMMMMMMMMMMMMMMMMFDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDFMMMMMMMMMMMMMMMMMMMMMFAMAF",
            "FFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAMAFFFFFFFFFFFFFFFFFFFFFFFFAMAF",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
            "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
            "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
            "FFFGGGFFGGGFDGGGFFGGGFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFGGGFFGGGDDGGGFFGGGFF",
            "FFFFFFFFFFFFDDFFFFFFFFPPPPPPDDPPPPPPPPPPPPPPDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDPPPPPPPPPPPPPPDDPPPPFFFFFFFFFFDDFFFFFFFFFF",
            "FFFFFFFFFFFFDDFFFFFFFFPPPPPPDDPPPPPPPPPPPPPPDDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDPPPPPPPPPPPPPPDDPPPPFFFFFFFFFFDDFFFFFFFFFF",
            "FFFFFFFFFFFFDDFFFFFFFFFFFFMMDDMMMMMMMMMMMMMMDDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDMMMMMMMMMMMMMMDDFFFFFFFFFFFFFFDDFFFFFFFFFF",
            "FFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFF",
            "FFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFF",
            "AAAAAAAAAAAADDAAAAAAAAAAAAAADDAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAADDAAAAAAAAAAAAAADDAAAAAAAAAA",
            "FFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFF",
            "FFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFF",
            "FFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFF",
            "AAAAAAAAAAAADDAAAAAAAAAAAAAADDAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAADDAAAAAAAAAAAAAADDAAAAAAAAAA",
            "FFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFF",
            "FFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFF",
            "FFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFDDFFFFFFFFFF",
        ),
    )


    val gateTwelveSealed = PixelSprite(
        assetId = GATE_TWELVE_SCENE_ID,
        width = 128,
        height = 64,
        palette = mapOf(
            'B' to Color(0xFF111A20),
            'F' to Color(0xFF1B252C),
            'D' to Color(0xFF151E23),
            'P' to Color(0xFF263238),
            'A' to Color(0xFF3A4449),
            'M' to Color(0xFF4A555B),
            'L' to Color(0xFF66757C),
            'R' to PixelColors.Danger,
            'C' to PixelColors.Cyan,
            'G' to PixelColors.Gold,
            'p' to PixelColors.Paper,
        ),
        rows = listOf(
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMppppppMMMMMMMMMMMMMMMMppppppMMMMMMMMMMMMMMMMppppppMMMMMMMMMMMMMMMMppppppMMMMMMMMMMMMMMMMppppppMMMMMMMMBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMppppppMMMMMMMMMMMMMMMMppppppMMMMMMMMMMMMMMMMppppppMMMMMMMMMMMMMMMMppppppMMMMMMMMMMMMMMMMppppppMMMMMMMMBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBB",
        "BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMLLLLLLLLLLLpppppppppppppppppppppppppppppLLLLLLLLLLLLMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMLLLLLLLLLLLpppppppppppppppppppppppppppppLLLLLLLLLLLLMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDDDDDDPPPAAAMMMLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMAAAPPPDDDDDDDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDDDDDDPPPAAAMMMMDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDMMMMAAAPPPDDDDDDDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDDDDDDPPPAAAMMMMDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDMMMMAAAPPPDDDDDDDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDDDDDDPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPDDDDDDDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDDDDDDPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPDDDDDDDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDDDDDDPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPDDDDDDDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAAPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAAPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPAACCCCAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPAAAAAAAAAPPPPPPPPPPPPPPPPPDDDMMMMAAAAARRRRAAPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPAACCCCAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPACCCCCCCAPPPPPPPPPPPPPPPPPDDDMMMMAAAAARRRRAAPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDAACCCCAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPACCCCCCCAPPPPPPPPPPPPPPPPPDDDMMMMAAAAARRRRAADDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDAACCCCAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPACCCCCCCAPPPPPPPPPPPPPPPPPDDDMMMMAAAAARRRRAADDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPACCCCCCCAPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAADDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPACCCCCCCAPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAAPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPACCCCCCCAPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAAPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPAAAAAAAAAPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAAPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAAPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAADDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDDDDDDPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPDDDDDDDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPDDDDDDDDDDDDDDDPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPDDDDDDDDDDDDDDPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAPPPPPPPPPPPPPPPPPPPPAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAPPPPPPPPPPPPPPPPPPPPAABBBBBBBBBB",
        "BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAMMMMDDDPPPPPPPPPPPPPPPPPPPPPGGGPPPPPPPPPPPPPPPPPPPPDDDMMMMAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBB",
        "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
        "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
        "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFMMMMMMFFFFFFGGGGGGFFFFFFMMMMMMFFFFFFGGGGGGFFFFFFMMMMMMFFFFFFGGGGGGFFFFFFMMMMMMFFFFFFGGGGGGFFFFFFMMMMMMFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFMMMMMMFFFFFFGGGGGGFFFFFFMMMMMMFFFFFFGGGGGGFFFFFFMMMMMMFFFFFFGGGGGGFFFFFFMMMMMMFFFFFFGGGGGGFFFFFFMMMMMMFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
        ),
    )

    val serviceTunnelDefault: PixelSprite = run {
        val width = 128
        val height = 64
        val p = MutableList(height) { CharArray(width) { 'B' } }
        val palette = mapOf(
            'B' to Color(0xFF0B1114),
            'D' to Color(0xFF141D21),
            'P' to Color(0xFF202B30),
            'A' to Color(0xFF2D3A3F),
            'M' to Color(0xFF455157),
            'L' to Color(0xFF69757A),
            'F' to Color(0xFF10181B),
            'R' to Color(0xFF5A5346),
            'G' to Color(0xFFB38A4A),
            'C' to Color(0xFF6F9FB5),
        )

        fun rect(x: Int, y: Int, w: Int, h: Int, key: Char) {
            for (yy in y until y + h) for (xx in x until x + w) {
                if (xx in 0 until width && yy in 0 until height) p[yy][xx] = key
            }
        }

        fun line(
            x0: Int,
            y0: Int,
            x1: Int,
            y1: Int,
            key: Char,
            thickness: Int = 1,
        ) {
            var x = x0
            var y = y0
            val dx = kotlin.math.abs(x1 - x0)
            val sx = if (x0 < x1) 1 else -1
            val dy = -kotlin.math.abs(y1 - y0)
            val sy = if (y0 < y1) 1 else -1
            var err = dx + dy
            while (true) {
                rect(x - thickness / 2, y - thickness / 2, thickness, thickness, key)
                if (x == x1 && y == y1) break
                val e2 = 2 * err
                if (e2 >= dy) {
                    err += dy
                    x += sx
                }
                if (e2 <= dx) {
                    err += dx
                    y += sy
                }
            }
        }

        // Dark municipal service tunnel: deep arch, maintenance ribs, low work lighting.
        rect(0, 0, width, height, 'B')
        rect(0, 8, width, 48, 'D')
        rect(0, 45, width, 19, 'F')

        // Receding arch shells establish depth without a neon corridor treatment.
        val arches = listOf(
            intArrayOf(5, 8, 118, 48),
            intArrayOf(14, 11, 100, 42),
            intArrayOf(24, 14, 80, 36),
            intArrayOf(34, 17, 60, 30),
            intArrayOf(44, 20, 40, 24),
        )
        arches.forEachIndexed { index, a ->
            val key = if (index % 2 == 0) 'M' else 'A'
            rect(a[0], a[1], 3, a[3], key)
            rect(a[0] + a[2] - 3, a[1], 3, a[3], key)
            rect(a[0], a[1], a[2], 3, key)
        }

        // Central maintenance passage / vanishing-point gate.
        rect(49, 21, 30, 24, 'A')
        rect(53, 24, 22, 18, 'P')
        rect(57, 27, 14, 13, 'B')
        rect(62, 30, 4, 10, 'D')
        rect(63, 31, 2, 7, 'L')

        // Side utility panels, vents and restrained indicators.
        rect(9, 20, 16, 15, 'P')
        rect(12, 23, 10, 7, 'A')
        rect(14, 25, 6, 2, 'L')
        rect(103, 19, 16, 17, 'P')
        rect(106, 22, 10, 9, 'A')
        for (x in 108..114 step 3) rect(x, 24, 1, 5, 'B')
        rect(17, 31, 4, 2, 'C')
        rect(108, 32, 5, 2, 'C')

        // Amber maintenance lamps and wall brackets.
        listOf(
            intArrayOf(8, 16),
            intArrayOf(27, 18),
            intArrayOf(100, 18),
            intArrayOf(119, 16),
        ).forEach { lamp ->
            rect(lamp[0], lamp[1], 2, 5, 'M')
            rect(lamp[0] - 1, lamp[1] + 4, 4, 3, 'G')
        }

        // Pipes / cable runs hug the architecture instead of becoming glowing scenery.
        rect(3, 12, 44, 2, 'L')
        rect(81, 12, 44, 2, 'L')
        rect(6, 15, 39, 1, 'R')
        rect(83, 15, 39, 1, 'R')
        rect(4, 38, 30, 2, 'M')
        rect(94, 38, 30, 2, 'M')

        // Perspective rails and service walkway converge on the central passage.
        line(16, 63, 56, 39, 'L', 2)
        line(39, 63, 60, 39, 'R', 2)
        line(89, 63, 68, 39, 'R', 2)
        line(112, 63, 72, 39, 'L', 2)
        line(3, 58, 52, 40, 'A', 2)
        line(125, 58, 76, 40, 'A', 2)

        // Floor sleepers become narrower toward the vanishing point.
        listOf(
            intArrayOf(20, 59, 88),
            intArrayOf(27, 55, 74),
            intArrayOf(34, 51, 60),
            intArrayOf(41, 47, 46),
            intArrayOf(48, 44, 32),
        ).forEach { sleeper ->
            rect(sleeper[0], sleeper[1], sleeper[2], 2, 'R')
        }

        // Drainage / access details at the near foreground.
        rect(4, 53, 16, 4, 'P')
        for (x in 6..18 step 3) rect(x, 54, 1, 2, 'B')
        rect(108, 52, 15, 5, 'P')
        for (x in 110..120 step 3) rect(x, 53, 1, 3, 'B')
        rect(58, 56, 12, 3, 'A')
        rect(60, 57, 8, 1, 'G')

        PixelSprite(
            assetId = SERVICE_TUNNEL_SCENE_ID,
            width = width,
            height = height,
            palette = palette,
            rows = p.map { it.concatToString() },
        )
    }

    val evacStairDefault: PixelSprite = run {
        val width = 128
        val height = 64
        val p = MutableList(height) { CharArray(width) { 'B' } }
        val palette = mapOf(
            'B' to Color(0xFF0D1316),
            'D' to Color(0xFF171F22),
            'P' to Color(0xFF252E31),
            'A' to Color(0xFF333D3F),
            'M' to Color(0xFF4B5553),
            'L' to Color(0xFF747B73),
            'F' to Color(0xFF111719),
            'R' to Color(0xFF665B4D),
            'G' to Color(0xFFB99558),
            'H' to Color(0xFFD1B579),
            'S' to Color(0xFF40392F),
        )

        fun rect(x: Int, y: Int, w: Int, h: Int, key: Char) {
            for (yy in y until y + h) for (xx in x until x + w) {
                if (xx in 0 until width && yy in 0 until height) p[yy][xx] = key
            }
        }

        fun line(
            x0: Int,
            y0: Int,
            x1: Int,
            y1: Int,
            key: Char,
            thickness: Int = 1,
        ) {
            var x = x0
            var y = y0
            val dx = kotlin.math.abs(x1 - x0)
            val sx = if (x0 < x1) 1 else -1
            val dy = -kotlin.math.abs(y1 - y0)
            val sy = if (y0 < y1) 1 else -1
            var err = dx + dy
            while (true) {
                rect(x - thickness / 2, y - thickness / 2, thickness, thickness, key)
                if (x == x1 && y == y1) break
                val e2 = 2 * err
                if (e2 >= dy) {
                    err += dy
                    x += sx
                }
                if (e2 <= dx) {
                    err += dx
                    y += sy
                }
            }
        }

        // Quiet municipal maintenance stair: enclosed concrete/steel shaft with a long,
        // centered climb and restrained warm emergency lighting.
        rect(0, 0, width, height, 'B')
        rect(5, 5, 118, 55, 'D')
        rect(9, 8, 110, 48, 'P')

        // Recessed upper landing / closed utility doorway.
        rect(48, 7, 32, 18, 'A')
        rect(53, 10, 22, 13, 'D')
        rect(57, 13, 14, 10, 'B')
        rect(62, 15, 4, 8, 'M')
        rect(63, 17, 2, 3, 'G')
        rect(48, 24, 32, 2, 'L')

        // Wall panel rhythm and structural verticals.
        listOf(14, 30, 98, 114).forEach { x ->
            rect(x, 10, 3, 42, 'M')
            rect(x + 1, 13, 1, 36, 'L')
        }
        rect(18, 12, 11, 13, 'A')
        rect(20, 14, 7, 9, 'D')
        rect(99, 12, 11, 13, 'A')
        rect(101, 14, 7, 9, 'D')
        rect(19, 29, 10, 12, 'A')
        rect(21, 31, 6, 8, 'D')
        rect(99, 29, 10, 12, 'A')
        rect(101, 31, 6, 8, 'D')

        // Narrow maintenance lamps; amber only, no neon corridor wash.
        listOf(
            intArrayOf(21, 9),
            intArrayOf(105, 9),
            intArrayOf(22, 27),
            intArrayOf(104, 27),
            intArrayOf(24, 45),
            intArrayOf(102, 45),
        ).forEach { lamp ->
            rect(lamp[0], lamp[1], 4, 2, 'H')
            rect(lamp[0] + 1, lamp[1] + 2, 2, 2, 'G')
        }

        // Central stairwell: progressively wider treads toward the viewer.
        val steps = listOf(
            intArrayOf(57, 24, 14),
            intArrayOf(55, 27, 18),
            intArrayOf(53, 30, 22),
            intArrayOf(50, 33, 28),
            intArrayOf(47, 36, 34),
            intArrayOf(43, 39, 42),
            intArrayOf(39, 42, 50),
            intArrayOf(35, 45, 58),
            intArrayOf(31, 48, 66),
            intArrayOf(26, 51, 76),
            intArrayOf(20, 54, 88),
            intArrayOf(14, 57, 100),
        )
        steps.forEachIndexed { index, step ->
            rect(step[0], step[1], step[2], 3, if (index % 2 == 0) 'A' else 'M')
            rect(step[0] + 2, step[1], step[2] - 4, 1, 'L')
        }

        // Side stringers and rails converge on the landing.
        line(13, 62, 54, 25, 'R', 2)
        line(115, 62, 74, 25, 'R', 2)
        line(20, 54, 56, 25, 'L', 1)
        line(108, 54, 72, 25, 'L', 1)

        // Rail posts become progressively tighter with depth.
        listOf(
            intArrayOf(22, 54, 22, 46),
            intArrayOf(35, 46, 35, 39),
            intArrayOf(46, 39, 46, 33),
            intArrayOf(106, 54, 106, 46),
            intArrayOf(93, 46, 93, 39),
            intArrayOf(82, 39, 82, 33),
        ).forEach { post ->
            line(post[0], post[1], post[2], post[3], 'L', 1)
        }

        // Foreground landing / drainage threshold.
        rect(5, 60, 118, 4, 'F')
        rect(16, 60, 96, 2, 'S')
        for (x in 20..108 step 8) rect(x, 60, 3, 1, 'M')

        PixelSprite(
            assetId = EVAC_STAIR_SCENE_ID,
            width = width,
            height = height,
            palette = palette,
            rows = p.map { it.concatToString() },
        )
    }

    val traceChamberIdle = PixelSprite(
        assetId = TRACE_CHAMBER_SCENE_ID,
        width = 128,
        height = 64,
        palette = mapOf(
            'B' to Color(0xFF111A20),
            'F' to Color(0xFF1B252C),
            'D' to Color(0xFF162129),
            'P' to Color(0xFF26363E),
            'A' to Color(0xFF303E45),
            'M' to Color(0xFF48535A),
            'L' to Color(0xFF65737A),
            'R' to PixelColors.Danger,
            'C' to PixelColors.Cyan,
            'G' to PixelColors.Gold,
            'H' to Color(0xFFD29A55),
            'S' to Color(0xFF6A5941),
            'p' to PixelColors.Paper,
        ),
        rows = listOf(
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBB",
        "BBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBPPPPPPPPPPPPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCPPPPPPPPPPPPPPPPPPPPPPPPPPBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBPPPDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDPPPBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBPPPDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDPPPBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBPPPDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDPPPBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBGGGGGGGGBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBGGGGGGGGBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDCCCCDDDDDDDDDCCCCDDDDDAAAACCCCDDDDDDDDDCCCCDDDDDDDDDCCCCDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDCCCCDDDDDDDDDCCCCDDDDDAAAACCCCDDDDDDDDDCCCCDDDDDDDDDCCCCDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDCCCCDDDDDDDDDCCCCDDDDDAAAACCCCDDDDDDDDDCCCCDDDDDDDDDCCCCDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDCCCCDDDDDDDDDCCCCDDDDDAAAACCCCDDDDDDDDDCCCCDDDDDDDDDCCCCDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDLLLLLLLLLLLLLLLLLLLLLLLLDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDLLLLLLLLLLLLLLLLLLLLLLLLDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDLLLLLLLLLLLLLLLLLLLLLLLLDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPDDDDDDDDDDDDDDDDDDDDDDDDDMMMMMMMMMMMMMMMMDDDDDDDDDDDDDDDDDDDDDDDDDPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMMMMMMPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMMMMMMPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBPPPPPPPPPPPPPPPPPPPPPPPPPPPPMMMMMMMMMMMMMMMMPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBAAAABBBBBBBBBB",
        "BBBBBBBBBBAAAABBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBBBBBBBCCBBBBBBBBAAAABBBBBBBBBB",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
        ),
    )

    val districtPlazaOpen = PixelSprite(
        assetId = DISTRICT_PLAZA_SCENE_ID,
        width = 128,
        height = 64,
        palette = mapOf(
            'B' to Color(0xFF111A20),
            'F' to Color(0xFF1B252C),
            'D' to Color(0xFF162129),
            'P' to Color(0xFF26363E),
            'A' to Color(0xFF303E45),
            'M' to Color(0xFF48535A),
            'L' to Color(0xFF65737A),
            'R' to PixelColors.Danger,
            'C' to PixelColors.Cyan,
            'G' to PixelColors.Gold,
            'H' to Color(0xFFD29A55),
            'S' to Color(0xFF6A5941),
            'p' to PixelColors.Paper,
        ),
        rows = listOf(
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMDDDDDDDDDDMMMMDDDDDDDDDDMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAPPPPPPPPPPPPPPPPPPPPPPPPPPAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAPPPPPPPPPPPPPPPPPPPPAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRRRRBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAARRRRRRAAAAAAAARRRRRRBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBGGGGGBAAAAAAAAAAAGGGGGAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAARRRRRRAAAAAAAARRRRRRBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBGGGGGBAAAAAAAAAAAGGGGGAAAAAAAAAAAAAABBBBBBB",
        "BBBBBAAAAAAAAAAAAAAARRRRRRAAAAAAAARRRRRRBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBGGGGGBAAAAAAAAAAAGGGGGAAAAAAAAAAAAAABBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBRRRRRRBBBBBBBBRRRRRRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGBBBBBBBBBBBBGGGGGBBBBBBBBBBBBBBBBBBBBB",
        "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
        "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
        "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
        "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFF",
        "FFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFFFFFFMMMMMMMMFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
        ),
    )

    val districtArchiveDefault = PixelSprite(
        assetId = DISTRICT_ARCHIVE_SCENE_ID,
        width = 128,
        height = 64,
        palette = mapOf(
            'B' to Color(0xFF111A20),
            'F' to Color(0xFF1B252C),
            'D' to Color(0xFF162129),
            'P' to Color(0xFF26363E),
            'A' to Color(0xFF303E45),
            'M' to Color(0xFF48535A),
            'L' to Color(0xFF65737A),
            'R' to PixelColors.Danger,
            'C' to PixelColors.Cyan,
            'G' to PixelColors.Gold,
            'H' to Color(0xFFD29A55),
            'S' to Color(0xFF6A5941),
            'p' to PixelColors.Paper,
        ),
        rows = listOf(
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPDDDDDDDDDDDDDDDDDPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPDDDDDDDDDDDDDDDDDPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPDDDDCCCCCCCCCDDDDPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPDDDDCCCCCCCCCDDDDPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPDDDDCCCCCCCCCDDDDPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPDDDDDDDDDDDDDDDDDPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPDDDDDDDDDDDDDDDDDPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMSSSSSSSSSSSSSSSSMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMCCCMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
        ),
    )

    val workshopRowDefault = PixelSprite(
        assetId = WORKSHOP_ROW_SCENE_ID,
        width = 128,
        height = 64,
        palette = mapOf(
            'B' to Color(0xFF111A20),
            'F' to Color(0xFF1B252C),
            'D' to Color(0xFF162129),
            'P' to Color(0xFF26363E),
            'A' to Color(0xFF303E45),
            'M' to Color(0xFF48535A),
            'L' to Color(0xFF65737A),
            'R' to PixelColors.Danger,
            'C' to PixelColors.Cyan,
            'G' to PixelColors.Gold,
            'H' to Color(0xFFD29A55),
            'S' to Color(0xFF6A5941),
            'p' to PixelColors.Paper,
        ),
        rows = listOf(
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBB",
        "BBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBB",
        "BBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBBBBBAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBB",
        "BBBBAAAAAAAACCCCCCAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAAAAABBBBBBBBAAAADDDDDDDDDDDDDDDDDDDDDDDDDDAAAABBBBB",
        "BBBBAAAAAAAACCCCCCAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAAAAABBBBBBBBAAAADDDDDDDDRRRRRRDDDDDDDDDDDDAAAABBBBB",
        "BBBBAAAAAAAACCCCCCAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAARRRRRRAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAAAAACCCCCCAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAARRRRRRAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAAAAACCCCCCAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAARRRRRRAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAAAAAAAAARRRRRRAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBB",
        "BBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBB",
        "BBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMMMMMMMMMAAAAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBB",
        "BBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMMMMMMMMMAAAAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMMMMMCCCCCCAAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSSSSSSSSSSSAAAAABBBBB",
        "BBBBAAAAAAAAMMMMMMMMMMLLLLLLLMAAAAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMMMMMCCCCCCAAAAAABBBBBBBBAAAAASSSSSSSSSSSSSSGGGGGGSSSSAAAAABBBBB",
        "BBBBAAAAAAAAMMMMMMMMMMLLLLLLLMAAAAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMMMMMCCCCCCAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAGGGGGGAAAAAAAAABBBBB",
        "BBBBAAAAAAAAMMMMMMMMMMLLLLLLLMAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAACCCCCCAAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMGGGGGGMAAAAAAAABBBBB",
        "BBBBAAAAAAAAMMMMMMMMMMLLLLLLLMAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAACCCCCCAAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMGGGGGGMAAAAAAAABBBBB",
        "BBBBAAAAAAAAMMMMMMMMMMMMMMMMMMAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMMMMMMMMAAAAAAAABBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMMMMMMMMAAAAAAAABBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAMMMMMMMMMMMMMMMMMMAAAAAAAABBBBB",
        "BBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
        ),
    )

    val productionScenes: List<PixelSprite> = listOf(
        platformNineBlackout,
        relayWorkbenchDefault,
        gateTwelveSealed,
        serviceTunnelDefault,
        evacStairDefault,
        traceChamberIdle,
        districtPlazaOpen,
        districtArchiveDefault,
        workshopRowDefault,
    )

    fun scene(locationId: String): PixelSprite? =
        when (locationId) {
            "PLATFORM_NINE" -> platformNineBlackout
            "RELAY_WORKBENCH" -> relayWorkbenchDefault
            "GATE_TWELVE" -> gateTwelveSealed
            "SERVICE_TUNNEL" -> serviceTunnelDefault
            "EVAC_STAIR" -> evacStairDefault
            "TRACE_CHAMBER" -> traceChamberIdle
            "DISTRICT_PLAZA" -> districtPlazaOpen
            "DISTRICT_ARCHIVE" -> districtArchiveDefault
            "WORKSHOP_ROW" -> workshopRowDefault
            else -> null
        }
}
